version: '3'
services:   

    local.azurefunctions:
        build:
          context: .
          dockerfile: Dockerfile
        ports:
          - 8080:80
        environment:
          - RabbitMQ=aqmp://guest:guest@192.168.1.250:5672
        volumes:
          - /downloadoutput:/mnt/user/Adult/temp