version: '3'
services:   

    local.azurefunctions:
        container_name: local.azurefunctions
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8080:80
        environment:
            # Copy .env variables through to container
            - RabbitMQ