version: '3'
services:
	local.functions:
		container_name: AzureFunctions
		build:
			context: .
			dockerfile: Dockerfile
		ports:
			- 8080:80
		environment:
			# copy .env variables through to container_name
			- RabbitMQ